services:
  backend-python:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: NikolaTeslApp-backend
    # ports:
    #   - "9008:3000"
    networks:
      - NikolaTeslApp-network
      # - reverse-proxy-network

  react-app:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    container_name: NikolaTeslApp-frontend
    networks:
      - NikolaTeslApp-network
    #  - reverse-proxy-network
    depends_on:
      - backend-python

  proxy:
    image: nginx:alpine
    container_name: NikolaTeslApp-proxy
    ports:
      - "9011:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - NikolaTeslApp-network

networks:
  NikolaTeslApp-network:
    driver: bridge
#  reverse-proxy-network:
#    external: true  # Réseau partagé avec le reverse proxy
